// ========================================
// AyurGenix – Input Types & Quiz Data Only
// No hardcoded recommendations — all generated by LLM
// ========================================

export type Dosha = 'vata' | 'pitta' | 'kapha';

// ---- Prakriti Quiz Questions (UI only) ----
export interface QuizQuestion {
    id: string;
    category: string;
    icon: string;
    question: string;
    options: { label: string; value: string }[];
}

export const prakritiQuestions: QuizQuestion[] = [
    {
        id: 'body_frame', category: 'Body Frame', icon: '🦴',
        question: 'What best describes your body frame?',
        options: [
            { label: 'Thin, light, hard to gain weight', value: 'thin' },
            { label: 'Medium build, muscular, athletic', value: 'medium' },
            { label: 'Heavy, broad, gains weight easily', value: 'heavy' },
        ],
    },
    {
        id: 'skin_type', category: 'Skin', icon: '✋',
        question: 'How would you describe your skin?',
        options: [
            { label: 'Dry, rough, thin, cool to touch', value: 'dry' },
            { label: 'Warm, oily, prone to rashes or acne', value: 'warm' },
            { label: 'Thick, smooth, oily, pale', value: 'thick' },
        ],
    },
    {
        id: 'hair', category: 'Hair', icon: '💇',
        question: 'What best describes your hair?',
        options: [
            { label: 'Dry, frizzy, thin, tends to tangle', value: 'dry' },
            { label: 'Fine, straight, premature greying', value: 'fine' },
            { label: 'Thick, lustrous, wavy, oily', value: 'thick' },
        ],
    },
    {
        id: 'digestion', category: 'Digestion', icon: '🫄',
        question: 'How is your digestion typically?',
        options: [
            { label: 'Irregular, bloating, gas, constipation', value: 'irregular' },
            { label: 'Strong, acidic, heartburn if skipping meals', value: 'strong' },
            { label: 'Slow but steady, heavy feeling after meals', value: 'slow' },
        ],
    },
    {
        id: 'appetite', category: 'Appetite', icon: '🍽️',
        question: 'How would you describe your appetite?',
        options: [
            { label: 'Variable — sometimes hungry, sometimes not', value: 'variable' },
            { label: 'Strong — I get very hungry and irritable', value: 'strong' },
            { label: 'Moderate — I can skip meals without issue', value: 'moderate' },
        ],
    },
    {
        id: 'sleep', category: 'Sleep', icon: '😴',
        question: 'How is your sleep pattern?',
        options: [
            { label: 'Light, intermittent, hard to fall asleep', value: 'light' },
            { label: 'Moderate, wake up feeling ready', value: 'moderate' },
            { label: 'Heavy, deep, hard to wake up', value: 'heavy' },
        ],
    },
    {
        id: 'energy', category: 'Energy Pattern', icon: '⚡',
        question: 'How does your energy fluctuate?',
        options: [
            { label: 'Variable — high energy bursts then crashes', value: 'variable' },
            { label: 'Intense and focused, driven until burnout', value: 'intense' },
            { label: 'Steady, stable, slow to start but consistent', value: 'steady' },
        ],
    },
    {
        id: 'emotions', category: 'Emotional Nature', icon: '💭',
        question: 'Under stress, you tend to feel…',
        options: [
            { label: 'Anxious, fearful, restless, overthinking', value: 'anxious' },
            { label: 'Irritable, angry, impatient, critical', value: 'irritable' },
            { label: 'Withdrawn, sad, unmotivated, attached', value: 'withdrawn' },
        ],
    },
    {
        id: 'climate', category: 'Climate Preference', icon: '🌡️',
        question: 'Which climate makes you feel best?',
        options: [
            { label: 'Warm, humid — I dislike cold & wind', value: 'warm_humid' },
            { label: 'Cool climates — I overheat easily', value: 'cool' },
            { label: 'Warm & dry — I dislike damp & cold', value: 'warm_dry' },
        ],
    },
    {
        id: 'mind', category: 'Mental Activity', icon: '🧠',
        question: 'How would you describe your thinking style?',
        options: [
            { label: 'Quick learner but forgets fast, creative', value: 'quick' },
            { label: 'Sharp, analytical, detail-oriented', value: 'sharp' },
            { label: 'Slow to learn but excellent long-term memory', value: 'slow_steady' },
        ],
    },
];

// ---- Symptom Options for Health Assessment ----
export const symptomOptions = [
    'Acidity / Heartburn', 'Hair Fall', 'Stress / Anxiety', 'Sleep Issues / Insomnia',
    'Weight Gain', 'Unexplained Weight Loss', 'Acne / Skin Breakouts', 'Constipation',
    'Bloating / Gas', 'Thyroid Concerns', 'Low Immunity', 'Chronic Fatigue',
    'Joint Pain / Stiffness', 'Frequent Headaches', 'Dry Skin / Lips',
    'Irregular Periods', 'Back Pain', 'Eye Strain', 'Mood Swings', 'Poor Concentration',
];

// ---- Mental Health Options ----
export const mentalHealthOptions = [
    'Anxiety', 'Depression', 'Chronic Stress', 'Panic Attacks',
    'Overthinking / Racing Thoughts', 'Emotional Eating', 'Low Motivation',
    'Anger Management Issues', 'Social Anxiety', 'PTSD / Trauma',
    'OCD Tendencies', 'Brain Fog', 'Low Self-Esteem', 'Burnout',
];

// ---- Common Diseases ----
export const commonDiseases = [
    'Weight Management', 'Hair Fall / Alopecia', 'Acne / Skin Issues', 'Constipation / IBS',
    'Stress & Anxiety', 'Diabetes (Type 2)', 'PCOS / PCOD', 'Thyroid Issues',
    'Insomnia / Sleep Disorders', 'Acid Reflux / GERD', 'Joint Pain / Arthritis',
    'Low Immunity', 'Migraine / Headaches', 'High Blood Pressure',
    'Skin Allergies / Eczema', 'Asthma / Respiratory Issues',
    'Digestive Disorders', 'Kidney Stones', 'Liver Issues', 'Anemia',
];

// ---- Disease Severity Options ----
export const severityOptions = ['Mild', 'Moderate', 'Severe'];

// ---- Duration Options ----
export const durationOptions = [
    'Less than 1 month', '1-3 months', '3-6 months',
    '6 months - 1 year', '1-2 years', '2-5 years', 'More than 5 years',
];

// ---- Eating Habit Options ----
export const eatingHabitOptions = [
    'Regular meals at fixed times',
    'Irregular / skips meals often',
    'Loves spicy food',
    'Prefers cold / raw food',
    'Eats a lot of junk / processed food',
    'Late night eating',
    'Eats very fast',
    'Overeats frequently',
    'Very small portions',
];

// ---- Stress Level Options ----
export const stressLevelOptions = ['Low', 'Moderate', 'High', 'Very High'];

// ---- Activity Level Options ----
export const activityLevelOptions = ['Sedentary', 'Light', 'Moderate', 'Active', 'Very Active'];

// ---- Dietary Preference Options ----
export const dietaryPreferenceOptions = ['Vegetarian', 'Non-Vegetarian', 'Vegan', 'Eggetarian'];

// ---- Red Flag Symptoms (always show warning) ----
export const redFlagSymptoms = [
    'Chest pain', 'Severe diabetes symptoms', 'Sudden unexplained weight loss',
    'High fever for extended periods', 'Difficulty breathing',
    'Blood in stool or urine', 'Severe abdominal pain', 'Fainting or loss of consciousness',
];

// ---- User Profile Shape ----
export interface UserProfile {
    name: string;
    age: number;
    gender: string;
    weight: number;    // kg
    height: number;    // cm
    activityLevel: string;
    dietaryPreference: string;
    existingConditions: string[];
    currentMedications: string;
    prakritiAnswers: Record<string, string>;
    symptoms: string[];
    season: string;
    language: string;
}

// ---- BMI Calculator (simple math, no LLM needed) ----
export function calculateBMI(weightKg: number, heightCm: number) {
    const heightM = heightCm / 100;
    const bmi = weightKg / (heightM * heightM);
    let category = '';
    let color = '';
    if (bmi < 18.5) { category = 'Underweight'; color = '#40c4ff'; }
    else if (bmi < 25) { category = 'Normal'; color = '#00e676'; }
    else if (bmi < 30) { category = 'Overweight'; color = '#ffab00'; }
    else { category = 'Obese'; color = '#ff5252'; }
    return { bmi: Math.round(bmi * 10) / 10, category, color };
}

// ---- Hydration Calculator (simple math) ----
export function calculateHydration(weightKg: number, season: string, activityLevel: string) {
    let base = weightKg * 35;
    if (season === 'summer') base += 500;
    else if (season === 'monsoon') base += 200;
    else if (season === 'winter') base -= 200;
    if (activityLevel === 'active') base += 300;
    else if (activityLevel === 'sedentary') base -= 100;
    return { totalMl: Math.round(base), glasses: Math.round(base / 250), liters: (base / 1000).toFixed(1) };
}
